// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Client struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.NullUUID  `json:"user_id"`
	Domain      string         `json:"domain"`
	Secret      []byte         `json:"secret"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Logo        sql.NullString `json:"logo"`
	Internal    bool           `json:"internal"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Token struct {
	ID                  uuid.UUID      `json:"id"`
	ClientID            uuid.UUID      `json:"client_id"`
	UserID              uuid.NullUUID  `json:"user_id"`
	RedirectUri         string         `json:"redirect_uri"`
	Scope               string         `json:"scope"`
	Code                string         `json:"code"`
	CodeChallenge       string         `json:"code_challenge"`
	CodeChallengeMethod string         `json:"code_challenge_method"`
	CodeCreateAt        time.Time      `json:"code_create_at"`
	CodeExpiresIn       int64          `json:"code_expires_in"`
	AccessID            uuid.UUID      `json:"access_id"`
	AccessCreateAt      time.Time      `json:"access_create_at"`
	AccessExpiresIn     int64          `json:"access_expires_in"`
	RefreshID           uuid.UUID      `json:"refresh_id"`
	RefreshCreateAt     time.Time      `json:"refresh_create_at"`
	RefreshExpiresIn    int64          `json:"refresh_expires_in"`
	UserAgent           sql.NullString `json:"user_agent"`
	IpAddress           sql.NullString `json:"ip_address"`
}

type User struct {
	ID        uuid.UUID    `json:"id"`
	Email     string       `json:"email"`
	Password  []byte       `json:"password"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type UserVerification struct {
	RequestType      int32     `json:"request_type"`
	UserID           uuid.UUID `json:"user_id"`
	Email            string    `json:"email"`
	VerificationCode []byte    `json:"verification_code"`
	ExpiresAt        time.Time `json:"expires_at"`
	CreatedAt        time.Time `json:"created_at"`
}
